exports.CATEGORY_ANIME = 'ANIME';
exports.CATEGORY_CRIME = 'CRIME';
exports.CATEGORY_DRAMA = 'DRAMA';
exports.CATEGORY_THRILLER = 'THRILLER';
exports.CATEGORY_HORROR = 'HORROR';
exports.CATEGORY_FAMILY = 'FAMILY';
exports.CATEGORY_TV_SHOWS = 'TV_SHOWS';
exports.CATEGORY_ROMANCE = 'ROMANCE';
exports.CATEGORY_COMEDY = 'COMEDY';
exports.CATEGORY_FANTASY = 'FANTASY';
exports.CATEGORY_ACTION = 'ACTION';
exports.CATEGORY_DOCUMENTARY = 'DOCUMENTARY';

exports.ROLE_ADMIN = 'ADMIN';
exports.ROLE_USER = 'USER';
